### ISSUE TITLE
Reboot plan

### ISSUE THREAD

**Issue by glidester** [piotrga/async-dynamo#13]
So after yesterday's enthusiasm we need to plan how to get things moving again and draw in all the improvements made in the various forks.

I'm not all that familiar with all the functionality of Git hub, I only discovered yesterday that there are currently 14 different forks of this project. Only 5 have committed changes to them. Here is a shout out to the other contributors of those forks @madsmith , @bkempe and @jlaws

I've gone through the commits of the 5 forks and summarised them. Not sure if we should be discussing this stuff in an 'Issue' but I don't know where else to atm.

There are quite a lot of similar commits dealing with the same issues (compiler warnings, library upgrades etc....) which will be pretty uncontentious to pull in. There are also a couple of places where the contributors have gone different ways which we will need to discuss which way to follow (definition of hash and range keys in the DynamoObject class for instance).

We should also decide how to pull these changes back into this repo, pull requests or just create new commits (might be a cleaner way, don't know)?

I'll publish my notes on the various commits in a separate post.

Just to reiterate I've not got a lot of experience of doing this type of stuff so I'm more than happy to take guidance from others.

Cheers,

Tim

**Comment by alexanderdean** [comment]
Reboot is complete.
