### ISSUE TITLE
Add in support for Scala 2.11

### ISSUE THREAD

**Issue by alexanderdean** [piotrga/async-dynamo#31]

**Comment by petervandenabeele** [comment]
A 2.11 version would be great ... Currently fighting with:

```
[warn] ==== Snowplow Analytics Maven repo: tried
[warn]   http://maven.snplow.com/releases/com/github/piotrga/async-dynamo_2.11/2.0.0/async-dynamo_2.11-2.0.0.pom
```

in my Scala 2.11 project (when I replace 2.11 with 2.10 I do find a version).

Anyway to circumvent this for now ?

PS. reverted to 2.10.5 for now, and now I can make progress.

**Comment by josh-padnick** [comment]
+1. Ran into this myself. I'll try the fix suggested by @petervandenabeele .  Scala 2.11 came out about 13 months ago, so this would be a welcome update!

**Comment by cjwebb** [comment]
Is there anything we can do to expedite the support for Scala 2.11?

**Comment by alexanderdean** [comment]
PR welcome!

**Comment by cjwebb** [comment]
I can't promise anything, but I'll have a play around :)

Have you investigated what is required to do this? Is there a task-list?
From a quick glance, it looks like we need to upgrade ScalaTest & Akka dependencies...

**Comment by alexanderdean** [comment]
Duplicate of #35
